### PR TITLE
Add extra support guidance for Minecraft

### PR DESCRIPTION
**Pull request by karianna**

### CODE REVIEW

**Review by gdams — APPROVED** [review]

**Comment by tellison** [comment]
I applaud your knowledge of Minecraft crash detection?!

**Comment by karianna** [comment]
Shamelessly copied from 3 years of support at MSFT ;-)

**Comment by supriya-SikkaAI** [comment]
I am trying to install Java on ec2 instances using flintrock, however, I am getting the below error while trying to download temurin jdk (temurin java 11) from https://packages.adoptium.net/artifactory/rpm/centos/8/.  The page shows 404 error when clicked on the link, not sure if there has been any change in path in the last week. 
image (6)

image (6)

**Comment by SupriyaRamachandra** [comment]
I am trying to install Java on ec2 instances using flintrock, however, I am getting the below error while trying to download temurin jdk (temurin java 11) from https://packages.adoptium.net/artifactory/rpm/centos/8/. The page shows 404 error when clicked on the link, not sure if there has been any change in path in the last week.
image (6)

**Pull request merged**
